apiVersion: apps/v1
kind: Deployment
metadata:
    name: home
spec:
    replicas: 2
    selector:
        matchLabels:
            app: home
    template:
        metadata:
            labels:
                app: home
        spec:
            containers:
                - name: home-container
                  image: public.ecr.aws/o6i8p2j4/storefront-poc:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: NODE_ENV
                        value: 'production'
