import { useEffect } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'POC-EASY',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	useEffect(() => {
		if (window.location.pathname === '/no_null.html') {
			// Utiliza la API history para manipular la URL sin redireccionar
			const newUrl =
				window.location.origin +
				window.location.pathname.replace('/no_null.html', '');
			window.history.replaceState({}, document.title, newUrl);
		}
	}, []);

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
