name: Deploy to Amazon EKS
run-name: ${{github.actor}} is deploying to Amazon EKS
on:
    push:
        branches:
            - main
env:
    BUILD_DIRECTORY: ${{secrets.MICRO_NAME}}-${{ github.sha }}
jobs:
    prepare-project-to-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies and build project
              run: |
                  npm install
                  npm run build
                  mkdir ${{ env.BUILD_DIRECTORY }}/_next
                  cp -r ${{ env.BUILD_DIRECTORY }}/static ${{ env.BUILD_DIRECTORY }}/_next/

            - name: Upload files to artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: |
                      .
                      !node_modules
                      !.git
                      !.github/*
                      !src
                      !Dockerfile
    send-to-s3-and-ecr:
        runs-on: ubuntu-latest
        needs: prepare-project-to-deploy
        steps:
            - name: Download files from artifact
              uses: actions/download-artifact@v3
              with:
                  name: build
                  path: .
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - name: Upload files to S3
              run: aws s3 cp ${{ env.BUILD_DIRECTORY }}/_next s3://${{secrets.S3_BUCKET_NAME}}/${{env.BUILD_DIRECTORY}}/_next --recursive
            - name: Login to Amazon ECR
              run: aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.AWS_ACCOUNT_ALIAS }}
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.PROJECT_NAME }} .
                  docker tag ${{ secrets.PROJECT_NAME }}:latest  public.ecr.aws/${{ secrets.AWS_ACCOUNT_ALIAS }}/${{ secrets.PROJECT_NAME }}:${{ github.sha }}
                  docker push public.ecr.aws/${{ secrets.AWS_ACCOUNT_ALIAS }}/${{ secrets.PROJECT_NAME }}:${{ github.sha }}
    deploy-to-eks:
        runs-on: ubuntu-latest
        needs: send-to-s3-and-ecr
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - name: Deploy to Amazon EKS
              env:
                  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
                  AWS_ACCOUNT_ALIAS: ${{ secrets.AWS_ACCOUNT_ALIAS }}
                  SHA: ${{ github.sha }}
              run: |
                  aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
                  kubectl apply -f k8s/
